### PR TITLE
Missing Error Message

### PR DESCRIPTION
**Pull request by porcupinenick**
Missing Error Message

### CODE REVIEW

**Comment by dlaptev** [comment]
Thanks for improving the documentation! However, this will not work. Your previous pull request worked correctly, but this solution was already mentioned in [the following section](https://github.com/LightningTo-Me/manuals/blob/master/Channel_Request.md#various-connection-and-timeout-errors). I will try to make it a bit easier to find.

**Comment by porcupinenick** [comment]
Hey Dmitry,

Thank you for reviewing my PR. However, I’m not seeing where it addresses the improperly formed public key error that I was getting on the docs. Where are you seeing this error getting addressed not eh current docs? 

Also, my previous PR was not correct, as the error was not related to Tor issues.

Thanks,
Nick

**Comment by dlaptev** [comment]
It does not matter if you include the IP address or not, it will be ignored anyway. The connection issues you had were because of Tor address, but not related to the how you format the request.

**Comment by porcupinenick** [comment]
Ok, then could I reopen my PR and have that merged instead?

**Comment by dlaptev** [comment]
Your first PR proposes the solution that was already described in the following section.

**Comment by porcupinenick** [comment]
ok, but can we make an explicit section mentioning the specific error message? I couldn’t find that specific error message in the docs.

**Comment by dlaptev** [comment]
There is a section for connection errors, and it has a range of bullet points, because there are many possible reasons for these errors, not only Tor. I updated the doc slightly to mention the error.

**Comment by porcupinenick** [comment]
Ok, great! Thanks once again for the service and I look forward to contributing to the project any way I can!

**Pull request closed without merging**
